In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, date

pd.set_option('display.max_columns', None)
data = pd.read_csv('Terry_stops.csv')
data.head(50)

,Subject Age Group,Subject ID,GO / SC Num,Terry Stop ID,Stop Resolution,Weapon Type,Officer ID,Officer YOB,Officer Gender,Officer Race,Subject Perceived Race,Subject Perceived Gender,Reported Date,Reported Time,Initial Call Type,Final Call Type,Call Type,Officer Squad,Arrest Flag,Frisk Flag,Precinct,Sector,Beat
0,-,-1,20140000120677,92317,Arrest,None,7500,1984,M,Black or African American,Asian,Male,2015-10-16T00:00:00,11:32:00,-,-,-,SOUTH PCT 1ST W - ROBERT,N,N,South,O,O2
1,-,-1,20150000001463,28806,Field Contact,None,5670,1965,M,White,-,-,2015-03-19T00:00:00,07:59:00,-,-,-,NaN,N,N,-,-,-
2,-,-1,20150000001516,29599,Field Contact,None,4844,1961,M,White,White,Male,2015-03-21T00:00:00,19:12:00,-,-,-,NaN,N,-,-,-,-
3,-,-1,20150000001670,32260,Field Contact,None,7539,1963,M,White,-,-,2015-04-01T00:00:00,04:55:00,-,-,-,NaN,N,N,-,-,-
4,-,-1,20150000001739,33155,Field Contact,None,6973,1977,M,White,Black or African American,Male,2015-04-03T00:00:00,00:41:00,-,-,-,NaN,N,N,-,-,-
5,-,-1,20150000001755,33571,Field Contact,None,7402,1973,M,White,Black or African American,Male,2015-04-05T00:00:00,23:46:00,-,-,-,NaN,N,N,-,-,-
6,-,-1,20150000002351,45252,Field Contact,None,7591,1985,M,Hispanic or Latino,Other,Female,2015-05-20T00:00:00,21:39:00,-,-,-,WEST PCT 3RD W - MARY,N,N,-,-,-
7,-,-1,20150000002363,45182,Field Contact,None,7591,1985,M,Hispanic or Latino,White,Male,2015-05-20T00:00:00,22:40:00,-,-,-,WEST PCT 3RD W - MARY,N,N,-,-,-
8,-,-1,20150000002392,45365,Field Contact,None,7560,1986,M,White,White,Female,2015-05-22T00:00:00,07:39:00,-,-,-,SOUTH PCT 1ST W - R/S RELIEF,N,N,East,E,E2
9,-,-1,20150000002451,46430,Field Contact,None,7591,1985,M,Hispanic or Latino,-,-,2015-05-25T00:00:00,01:06:00,-,-,-,WEST PCT 3RD W - MARY,N,N,-,-,-
10,-,-1,20150000002489,46918,Field Contact,None,6604,1973,M,Asian,Unknown,Male,2015-05-25T00:00:00,15:10:00,-,-,-,WEST PCT 2ND W - MARY BEATS,N,N,-,-,-
11,-,-1,20150000002583,48284,Field Contact,None,7501,1977,F,White,Unknown,Unable to Determine,2015-05-27T00:00:00,12:10:00,-,-,-,WEST PCT 2ND W - SPECIAL BEATS,N,-,-,-,-
12,-,-1,20150000002583,48285,Field Contact,None,7501,1977,F,White,Unknown,Unable to Determine,2015-05-27T00:00:00,12:26:00,-,-,-,WEST PCT 2ND W - SPECIAL BEATS,N,N,-,-,-
13,-,-1,20150000002604,48464,Field Contact,None,7771,1986,M,White,Unknown,Unable to Determine,2015-05-31T00:00:00,00:22:00,-,-,-,TRAINING - FIELD TRAINING SQUAD,N,N,-,-,-
14,-,-1,20150000002641,49096,Field Contact,None,6179,1964,M,American Indian/Alaska Native,-,Male,2015-06-01T00:00:00,02:05:00,-,-,-,NORTH PCT 3RD W - LINCOLN,N,N,East,C,C3
15,-,-1,20150000002677,49772,Field Contact,None,5065,1959,M,White,White,Male,2015-06-03T00:00:00,10:08:00,-,-,-,WEST PCT 2ND W - MARY BEATS,N,N,-,-,-
16,-,-1,20150000002678,49779,Field Contact,None,5065,1959,M,White,Black or African American,Male,2015-06-03T00:00:00,09:49:00,-,-,-,WEST PCT 2ND W - MARY BEATS,N,Y,-,-,-
17,-,-1,20150000002792,51543,Field Contact,None,7403,1973,M,White,-,-,2015-06-09T00:00:00,00:27:00,-,-,-,SOUTH PCT 3RD W - ROBERT,N,N,-,-,-
18,-,-1,20150000002815,51725,Field Contact,None,7456,1979,M,White,-,-,2015-06-09T00:00:00,19:27:00,-,-,-,NORTH PCT 2ND W - NORA,N,N,-,-,-
19,-,-1,20150000002815,51726,Field Contact,None,7456,1979,M,White,-,-,2015-06-09T00:00:00,19:31:00,-,-,-,NORTH PCT 2ND W - NORA,N,N,-,-,-
20,-,-1,20150000002815,51727,Field Contact,None,7456,1979,M,White,-,-,2015-06-09T00:00:00,19:32:00,-,-,-,NORTH PCT 2ND W - NORA,N,N,-,-,-
21,-,-1,20150000002823,52161,Field Contact,None,7540,1981,M,White,-,Unable to Determine,2015-06-11T00:00:00,00:08:00,-,-,-,NORTH PCT 2ND WATCH - B/N RELIEF,N,N,-,-,-
22,-,-1,20150000002833,52166,Field Contact,None,5966,1969,M,White,Other,Male,2015-06-11T00:00:00,00:58:00,-,-,-,WEST PCT 3RD W - K/Q RELIEF,N,N,-,-,-
23,-,-1,20150000002833,52167,Field Contact,None,5966,1969,M,White,American Indian or Alaska Native,Male,2015-06-11T00:00:00,01:21:00,-,-,-,WEST PCT 3RD W - K/Q RELIEF,N,N,-,-,-
24,-,-1,20150000002833,52168,Field Contact,None,5966,1969,M,White,American Indian or Alaska Native,Male,2015-06-11T00:00:00,01:25:00,-,-,-,WEST PCT 3RD W - K/Q RELIEF,N,N,-,-,-
25,-,-1,20150000002856,52559,Field Contact,None,7500,1984,M,Black or African American,Unknown,Unable to Determine,2015-06-12T00:00:00,04:44:00,-,-,-,SOUTH PCT 1ST W - ROBERT,N,N,-,-,-
26,-,-1,20150000002856,52560,Field Contact,None,7500,1984,M,Black or African American,Unknown,Unable to Determine,2015-06-12T00:00:00,04:50:00,-,-,-,SOUTH PCT 1ST W - ROBERT,N,N,-,-,-
27,-,-1,20150000002870,52057,Field Contact,None,7592,1983,M,White,Unknown,Unable to Determine,2015-06-12T00:00:00,14:32:00,-,-,-,SOUTH PCT 1ST W - ROBERT,N,N,-,-,-
28,-,-1,20150000003004,54532,Field Contact,None,7428,1963,M,Hispanic or Latino,White,Male,2015-06-17T00:00:00,21:48:00,-,-,-,WEST PCT 2ND W - MARY BEATS,N,N,-,-,-
29,-,-1,20150000003007,54535,Field Contact,None,7428,1963,M,Hispanic or Latino,Black or African American,Male,2015-06-17T00:00:00,22:08:00,-,-,-,WEST PCT 2ND W - MARY BEATS,N,Y,North,N,N3
30,-,-1,20150000003052,55088,Field Contact,None,7403,1973,M,White,-,-,2015-06-20T00:00:00,01:09:00,-,-,-,SOUTH PCT 3RD W - ROBERT,N,-,-,-,-
31,-,-1,20150000003188,57803,Citation / Infraction,None,7582,1966,M,Hispanic or Latino,Unknown,Unable to Determine,2015-06-27T00:00:00,05:12:00,-,-,-,SOUTH PCT 1ST W - R/S RELIEF,N,N,-,-,-
32,-,-1,20150000003206,58154,Field Contact,None,8316,1986,M,White,Unknown,Unable to Determine,2015-06-28T00:00:00,08:50:00,-,-,-,TRAINING - FIELD TRAINING SQUAD,N,N,-,-,-
33,-,-1,20150000003206,58155,Field Contact,None,8316,1986,M,White,Unknown,Unable to Determine,2015-06-28T00:00:00,09:05:00,-,-,-,TRAINING - FIELD TRAINING SQUAD,N,N,-,-,-
34,-,-1,20150000003266,58952,Field Contact,None,6313,1968,M,White,Asian,Female,2015-06-30T00:00:00,18:02:00,-,-,-,SOUTHWEST PCT 2ND W - WILLIAM,N,N,-,-,-
35,-,-1,20150000003266,58953,Field Contact,None,6313,1968,M,White,Asian,Male,2015-06-30T00:00:00,18:28:00,-,-,-,SOUTHWEST PCT 2ND W - WILLIAM,N,N,-,-,-
36,-,-1,20150000003315,59686,Field Contact,None,6417,1973,M,White,-,Male,2015-07-02T00:00:00,00:25:00,-,-,-,WEST PCT OPS - ACT NIGHT,N,N,-,-,-
37,-,-1,20150000003315,59687,Field Contact,None,6417,1973,M,White,-,Female,2015-07-02T00:00:00,00:37:00,-,-,-,WEST PCT OPS - ACT NIGHT,N,N,-,-,-
38,-,-1,20150000003333,59692,Field Contact,None,6417,1973,M,White,White,Male,2015-07-02T00:00:00,03:30:00,-,-,-,WEST PCT OPS - ACT NIGHT,N,N,-,-,-
39,-,-1,20150000003333,59693,Field Contact,None,6417,1973,M,White,White,Male,2015-07-02T00:00:00,03:46:00,-,-,-,WEST PCT OPS - ACT NIGHT,N,N,-,-,-
40,-,-1,20150000003365,60022,Field Contact,None,7728,1987,M,Two or More Races,-,-,2015-07-03T00:00:00,20:46:00,-,-,-,WEST PCT 2ND W - KING,N,N,-,-,-
41,-,-1,20150000003503,61978,Field Contact,None,8316,1986,M,White,Unknown,Unable to Determine,2015-07-10T00:00:00,06:24:00,-,-,-,TRAINING - FIELD TRAINING SQUAD,N,N,North,U,U1
42,-,-1,20150000003506,61980,Field Contact,None,8316,1986,M,White,Black or African American,Male,2015-07-10T00:00:00,08:46:00,-,-,-,TRAINING - FIELD TRAINING SQUAD,N,N,-,-,-
43,-,-1,20150000003542,62740,Field Contact,None,7582,1966,M,Hispanic or Latino,-,-,2015-07-13T00:00:00,07:05:00,-,-,-,SOUTH PCT 1ST W - R/S RELIEF,N,N,-,-,-
44,-,-1,20150000003542,62741,Field Contact,None,7582,1966,M,Hispanic or Latino,-,-,2015-07-13T00:00:00,07:21:00,-,-,-,SOUTH PCT 1ST W - R/S RELIEF,N,N,-,-,-
45,-,-1,20150000003561,63097,Field Contact,None,8316,1986,M,White,Black or African American,Male,2015-07-14T00:00:00,04:34:00,-,-,-,TRAINING - FIELD TRAINING SQUAD,N,N,-,-,-
46,-,-1,20150000003627,64251,Field Contact,Firearm Other,6040,1952,M,White,Unknown,Unable to Determine,2015-07-18T00:00:00,02:53:00,-,-,-,SOUTHWEST PCT 3RD W - WILLIAM,N,Y,-,-,-
47,-,-1,20150000003628,64252,Field Contact,Firearm Other,6040,1952,M,White,Unknown,Unable to Determine,2015-07-18T00:00:00,02:34:00,-,-,-,SOUTHWEST PCT 3RD W - WILLIAM,N,Y,-,-,-
48,-,-1,20150000003629,64263,Field Contact,Firearm Other,6040,1952,M,White,Unknown,Unable to Determine,2015-07-18T00:00:00,02:17:00,-,-,-,SOUTHWEST PCT 3RD W - WILLIAM,N,Y,-,-,-
49,-,-1,20150000003630,64264,Field Contact,Firearm Other,6040,1952,M,White,Unknown,Unable to Determine,2015-07-18T00:00:00,02:01:00,-,-,-,SOUTHWEST PCT 3RD W - WILLIAM,N,Y,-,-,-

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48485 entries, 0 to 48484
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Subject Age Group         48485 non-null  object
 1   Subject ID                48485 non-null  int64
 2   GO / SC Num               48485 non-null  int64
 3   Terry Stop ID             48485 non-null  int64
 4   Stop Resolution           48485 non-null  object
 5   Weapon Type               48485 non-null  object
 6   Officer ID                48485 non-null  object
 7   Officer YOB               48485 non-null  int64
 8   Officer Gender            48485 non-null  object
 9   Officer Race              48485 non-null  object
 10  Subject Perceived Race    48485 non-null  object
 11  Subject Perceived Gender  48485 non-null  object
 12  Reported Date             48485 non-null  object
 13  Reported Time             48485 non-null  object
 14  Initial Call Type         48485 non-null  object
 15  Final Call Type           48485 non-null  object
 16  Call Type                 48485 non-null  object
 17  Officer Squad             47879 non-null  object
 18  Arrest Flag               48485 non-null  object
 19  Frisk Flag                48485 non-null  object
 20  Precinct                  48485 non-null  object
 21  Sector                    48485 non-null  object
 22  Beat                      48485 non-null  object
dtypes: int64(4), object(19)
memory usage: 8.5+ MB

In [3]:
# removing unnecessary columns from dataframe
df = data.drop(columns=['Subject ID', 'GO / SC Num', 'Terry Stop ID', 'Reported Time'], axis=1)

In [4]:
# Inspection of Data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48485 entries, 0 to 48484
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Subject Age Group         48485 non-null  object
 1   Stop Resolution           48485 non-null  object
 2   Weapon Type               48485 non-null  object
 3   Officer ID                48485 non-null  object
 4   Officer YOB               48485 non-null  int64
 5   Officer Gender            48485 non-null  object
 6   Officer Race              48485 non-null  object
 7   Subject Perceived Race    48485 non-null  object
 8   Subject Perceived Gender  48485 non-null  object
 9   Reported Date             48485 non-null  object
 10  Initial Call Type         48485 non-null  object
 11  Final Call Type           48485 non-null  object
 12  Call Type                 48485 non-null  object
 13  Officer Squad             47879 non-null  object
 14  Arrest Flag               48485 non-null  object
 15  Frisk Flag                48485 non-null  object
 16  Precinct                  48485 non-null  object
 17  Sector                    48485 non-null  object
 18  Beat                      48485 non-null  object
dtypes: int64(1), object(18)
memory usage: 7.0+ MB

In [5]:
df.describe()

        Officer YOB
count  48485.000000
mean    1983.086893
std        9.083985
min     1900.000000
25%     1978.000000
50%     1985.000000
75%     1990.000000
max     1998.000000

In [6]:
#reformat col names 
df.rename(columns={'Subject Age Group':'subject_age_group', 'Stop Resolution':'stop_resolution', 'Weapon Type':'weapon_type', 'Officer ID':'officer_id',
       'Officer YOB':'officer_yob', 'Officer Gender':'officer_gender', 'Officer Race':'officer_race',
       'Subject Perceived Race':'subject_perceived_race', 'Subject Perceived Gender':'subject_perceived_gender', 'Reported Date':'reported_date',
       'Initial Call Type':'initial_call_type', 'Final Call Type':'final_call_type', 'Call Type':'call_type', 'Officer Squad': 'officer_squad',
       'Arrest Flag':'arrest_flag', 'Frisk Flag':'frisk_flag', 'Precinct':'precinct', 'Sector':'sector', 'Beat':'beat'}, inplace=True)

In [7]:
# Inspecting value counts for each column
for col in df.columns:
    try:
        print(df[col].value_counts())
    except:
        print(df[col].value_counts())   
    print('\n')

26 - 35         16158
36 - 45         10339
18 - 25          9669
46 - 55          6274
56 and Above     2466
1 - 17           1988
-                1591
Name: subject_age_group, dtype: int64


Field Contact               19691
Offense Report              15854
Arrest                      12032
Referred for Prosecution      728
Citation / Infraction         180
Name: stop_resolution, dtype: int64


None                                    32565
-                                       13021
Lethal Cutting Instrument                1482
Knife/Cutting/Stabbing Instrument         706
Handgun                                   300
Firearm Other                             100
Blunt Object/Striking Implement            93
Club, Blackjack, Brass Knuckles            49
Firearm                                    44
Mace/Pepper Spray                          31
Other Firearm                              27
Firearm (unk type)                         15
Taser/Stun Gun                             10
Club                                        9
None/Not Applicable                         9
Fire/Incendiary Device                      8
Rifle                                       7
Shotgun                                     3
Personal Weapons (hands, feet, etc.)        2
Automatic Handgun                           2
Brass Knuckles                              1
Blackjack                                   1
Name: weapon_type, dtype: int64


7456      430
7634      347
7773      333
7765      315
7758      313
         ...
5834        1
5712        1
8786        1
5917        1
8807        1
Name: officer_id, Length: 1225, dtype: int64


1986    3382
1987    3087
1984    2798
1991    2742
1992    2554
1985    2513
1990    2341
1988    2186
1989    2051
1982    1868
1983    1743
1979    1558
1993    1516
1981    1476
1995    1304
1971    1236
1978    1177
1976    1051
1977    1030
1994     963
1973     933
1980     838
1996     728
1967     721
1968     632
1970     612
1969     568
1974     565
1975     539
1997     486
1962     457
1964     439
1972     429
1965     420
1963     262
1966     228
1958     220
1961     215
1959     174
1960     161
1998      60
1954      44
1957      43
1900      35
1953      34
1955      21
1956      17
1948      11
1952       9
1949       5
1946       2
1951       1
Name: officer_yob, dtype: int64


M    42933
F     5523
N       29
Name: officer_gender, dtype: int64


White                            36494
Hispanic or Latino                2826
Two or More Races                 2785
Asian                             2118
Black or African American         1934
Not Specified                     1511
Nat Hawaiian/Oth Pac Islander      461
American Indian/Alaska Native      321
Unknown                             35
Name: officer_race, dtype: int64


White                                        23696
Black or African American                    14450
Unknown                                       2791
-                                             1853
Hispanic                                      1684
Asian                                         1590
American Indian or Alaska Native              1391
Multi-Racial                                   809
Other                                          152
Native Hawaiian or Other Pacific Islander       69
Name: subject_perceived_race, dtype: int64


Male                                                         38085
Female                                                        9793
Unable to Determine                                            326
-                                                              237
Unknown                                                         37
Gender Diverse (gender non-conforming and/or transgender)        7
Name: subject_perceived_gender, dtype: int64


2015-10-01T00:00:00    101
2015-09-29T00:00:00     66
2015-05-28T00:00:00     57
2015-07-18T00:00:00     55
2019-04-26T00:00:00     54
                      ...
2015-03-28T00:00:00      1
2015-05-10T00:00:00      1
2015-03-24T00:00:00      1
2015-05-06T00:00:00      1
2021-07-29T00:00:00      1
Name: reported_date, Length: 2328, dtype: int64


-                                                 13234
SUSPICIOUS STOP - OFFICER INITIATED ONVIEW         3234
SUSPICIOUS PERSON, VEHICLE OR INCIDENT             3097
DISTURBANCE, MISCELLANEOUS/OTHER                   2503
ASLT - IP/JO - WITH OR W/O WPNS (NO SHOOTINGS)     2104
                                                  ...
ESCAPE - PRISONER                                     1
MISSING - (ALZHEIMER, ENDANGERED, ELDERLY)            1
DEMONSTRATIONS                                        1
MISSING - ADULT                                       1
VICE - PORNOGRAPHY                                    1
Name: initial_call_type, Length: 168, dtype: int64


-                                              13234
--SUSPICIOUS CIRCUM. - SUSPICIOUS PERSON        3915
--PROWLER - TRESPASS                            3405
--DISTURBANCE - OTHER                           2799
--ASSAULTS, OTHER                               2381
                                               ...
-OFF DUTY EMPLOYMENT                               1
--DEMO MGMNT (CONTROL TACTICS USED)                1
PEACE-STANDBY TO ASSURE (NO COURT ORDR SVC)        1
TRAFFIC - MOVING VIOLATION                         1
TRAF - ELUDING POLICE                              1
Name: final_call_type, Length: 211, dtype: int64


911                              22098
-                                13234
ONVIEW                            9354
TELEPHONE OTHER, NOT 911          3428
ALARM CALL (NOT POLICE ALARM)      361
TEXT MESSAGE                         9
SCHEDULED EVENT (RECURRING)          1
Name: call_type, dtype: int64


TRAINING - FIELD TRAINING SQUAD                 5209
WEST PCT 1ST W - DAVID/MARY                     1582
WEST PCT 2ND W - D/M RELIEF                     1041
SOUTHWEST PCT 2ND W - FRANK                     1007
WEST PCT 1ST W - KING/QUEEN                      896
                                                ...
HR - BLEA - ACADEMY RECRUITS                       1
BURG/THEFT/JUV - WEST                              1
COMMUNITY OUTREACH - SPECIAL PROJECTS DETAIL       1
RECORDS - DAY SHIFT                                1
TRAINING - ADVANCED - SQUAD C                      1
Name: officer_squad, Length: 173, dtype: int64


N    44661
Y     3824
Name: arrest_flag, dtype: int64


N    37025
Y    10982
-      478
Name: frisk_flag, dtype: int64


West         11894
North        10664
-             9928
East          6382
South         5814
Southwest     2320
SouthWest     1225
Unknown        200
OOJ             37
FK ERROR        21
Name: precinct, dtype: int64


-         10139
E          2337
M          2270
N          2191
K          1877
K          1762
B          1658
L          1639
D          1512
R          1455
F          1378
M          1362
S          1348
U          1302
D          1248
O          1161
J          1119
G          1087
C          1037
E           990
Q           967
W           941
Q           892
N           765
F           753
R           682
O           655
B           596
S           514
G           497
U           489
L           482
W           471
C           433
J           423
99           53
Name: sector, dtype: int64


-         10073
N3         1175
E2         1092
K3         1054
M2          852
          ...
J2           86
99           53
99           35
OOJ          25
S             2
Name: beat, Length: 107, dtype: int64

In [8]:
# Some Columns have an '-' so will convert to NaN
#  and then inspect for NaN Values

df.replace('-', np.nan, inplace=True)
df.isna().sum()

subject_age_group            1591
stop_resolution                 0
weapon_type                 13021
officer_id                     24
officer_yob                     0
officer_gender                  0
officer_race                    0
subject_perceived_race       1853
subject_perceived_gender      237
reported_date                   0
initial_call_type           13234
final_call_type             13234
call_type                   13234
officer_squad                 606
arrest_flag                     0
frisk_flag                    478
precinct                     9928
sector                      10139
beat                        10073
dtype: int64

In [9]:
# Subject Age Group (10 year increments) as reported by the officer.

df['subject_age_group'].value_counts(dropna=False)

26 - 35         16158
36 - 45         10339
18 - 25          9669
46 - 55          6274
56 and Above     2466
1 - 17           1988
NaN              1591
Name: subject_age_group, dtype: int64

In [10]:
# Convert NaN to 'Not Specified'
df['subject_age_group'] = df['subject_age_group'].replace(np.nan,'Not Specified')

In [11]:
# Type of weapon, if any, identified during a search or frisk of the subject. Indicates "None" if no weapons was found.

df['weapon_type'].value_counts(dropna=False)

None                                    32565
NaN                                     13021
Lethal Cutting Instrument                1482
Knife/Cutting/Stabbing Instrument         706
Handgun                                   300
Firearm Other                             100
Blunt Object/Striking Implement            93
Club, Blackjack, Brass Knuckles            49
Firearm                                    44
Mace/Pepper Spray                          31
Other Firearm                              27
Firearm (unk type)                         15
Taser/Stun Gun                             10
Club                                        9
None/Not Applicable                         9
Fire/Incendiary Device                      8
Rifle                                       7
Shotgun                                     3
Personal Weapons (hands, feet, etc.)        2
Automatic Handgun                           2
Brass Knuckles                              1
Blackjack                                   1
Name: weapon_type, dtype: int64

In [12]:
# Converting NaN's to 'None' for weapon type column
df['weapon_type'] = df['weapon_type'].replace(np.nan,'None')

# Convert 'None/Not Applicable' to 'None' for alignment
df['weapon_type'] = df['weapon_type'].replace('None/Not Applicable','None')

In [13]:
# Key identifying unique officers in the dataset.
# possibly drop the 24 NaN's(?)

df['officer_id'].value_counts(dropna=False)

7456      430
7634      347
7773      333
7765      315
7758      313
         ...
6808        1
5664        1
5469        1
5994        1
6735        1
Name: officer_id, Length: 1225, dtype: int64

In [14]:
# Perceived race of the subject, as reported by the officer.

df['subject_perceived_race'].value_counts(dropna=False)

White                                        23696
Black or African American                    14450
Unknown                                       2791
NaN                                           1853
Hispanic                                      1684
Asian                                         1590
American Indian or Alaska Native              1391
Multi-Racial                                   809
Other                                          152
Native Hawaiian or Other Pacific Islander       69
Name: subject_perceived_race, dtype: int64

In [15]:
# Convert NaN's to Unknown so that they are aligned

df['subject_perceived_race'] = df['subject_perceived_race'].replace(np.nan,'Unknown')

In [16]:
# Perceived gender of the subject, as reported by the officer.

df['subject_perceived_gender'].value_counts(dropna=False)

Male                                                         38085
Female                                                        9793
Unable to Determine                                            326
NaN                                                            237
Unknown                                                         37
Gender Diverse (gender non-conforming and/or transgender)        7
Name: subject_perceived_gender, dtype: int64

In [17]:
#convert NaN's and 'Unable to determine' to 'Unknown' so that they are aligned

df['subject_perceived_gender'] = df['subject_perceived_gender'].replace(np.nan,'Unknown')
df['subject_perceived_gender'] = df['subject_perceived_gender'].replace('Unable to Determine','Unknown')

In [18]:
# Initial classification of the call as assigned by 911(?)
# possibly replace with officer intiated? SUSPICIOUS STOP - OFFICER INITIATED ONVIEW' or UNKNOWN - COMPLAINT OF UNKNOWN NATURE
df['initial_call_type'].value_counts(dropna=False)

NaN                                               13234
SUSPICIOUS STOP - OFFICER INITIATED ONVIEW         3234
SUSPICIOUS PERSON, VEHICLE OR INCIDENT             3097
DISTURBANCE, MISCELLANEOUS/OTHER                   2503
ASLT - IP/JO - WITH OR W/O WPNS (NO SHOOTINGS)     2104
                                                  ...
ESCAPE - PRISONER                                     1
MISSING - (ALZHEIMER, ENDANGERED, ELDERLY)            1
DEMONSTRATIONS                                        1
MISSING - ADULT                                       1
VICE - PORNOGRAPHY                                    1
Name: initial_call_type, Length: 168, dtype: int64

In [19]:
# Final classification of the call as assigned by the primary officer closing the event.
#possibly replace NAN's with 'UNKNOWN - COMPLAINT OF UNKNOWN NATURE' (?)
df['final_call_type'].value_counts(dropna=False)

NaN                                                  13234
--SUSPICIOUS CIRCUM. - SUSPICIOUS PERSON              3915
--PROWLER - TRESPASS                                  3405
--DISTURBANCE - OTHER                                 2799
--ASSAULTS, OTHER                                     2381
                                                     ...
-OFF DUTY EMPLOYMENT                                     1
--DEMO MGMNT (CONTROL TACTICS USED)                      1
--COMMERCIAL SEXUAL EXPLOITATION OF MINORS (CSEC)        1
UNDERCOVER OPS, CAUTION (INCLUDES STAKEOUTS)             1
TRAF - ELUDING POLICE                                    1
Name: final_call_type, Length: 211, dtype: int64

In [20]:
# How the call was received by the communication center.
df['call_type'].value_counts(dropna=False)

911                              22098
NaN                              13234
ONVIEW                            9354
TELEPHONE OTHER, NOT 911          3428
ALARM CALL (NOT POLICE ALARM)      361
TEXT MESSAGE                         9
SCHEDULED EVENT (RECURRING)          1
Name: call_type, dtype: int64

In [21]:
# Functional squad assignment (not budget) of the officer as reported by the Data Analytics Platform (DAP).
df['officer_squad'].value_counts(dropna=False)

TRAINING - FIELD TRAINING SQUAD                        5209
WEST PCT 1ST W - DAVID/MARY                            1582
WEST PCT 2ND W - D/M RELIEF                            1041
SOUTHWEST PCT 2ND W - FRANK                            1007
WEST PCT 1ST W - KING/QUEEN                             896
                                                       ...
SOUTHWEST PCT OPS - BURG/THEFT                            1
DV SQUAD D - ORDER SERVICE                                1
ZOLD CRIME ANALYSIS UNIT - ANALYSTS                       1
COMMUNITY OUTREACH - SPECIAL PROJECTS DETAIL              1
COMMUNITY OUTREACH - YOUTH VIOLENCE -SCHOOLS DETAIL       1
Name: officer_squad, Length: 174, dtype: int64

In [22]:
# Indicator of whether a "frisk" was conducted, by the officer, of the subject, during the Terry Stop.
df['frisk_flag'].value_counts(dropna=False)

N      37025
Y      10982
NaN      478
Name: frisk_flag, dtype: int64

In [23]:
# Precinct of the address associated with the underlying Computer Aided Dispatch (CAD) event. 
# Not necessarily where the Terry Stop occurred.

df['precinct'].value_counts(dropna=False)

West         11894
North        10664
NaN           9928
East          6382
South         5814
Southwest     2320
SouthWest     1225
Unknown        200
OOJ             37
FK ERROR        21
Name: precinct, dtype: int64

In [24]:
# Sector of the address associated with the underlying Computer Aided Dispatch (CAD) event. 
# Not necessarily where the Terry Stop occurred.

df['sector'].value_counts(dropna=False)

NaN       10139
E          2337
M          2270
N          2191
K          1877
K          1762
B          1658
L          1639
D          1512
R          1455
F          1378
M          1362
S          1348
U          1302
D          1248
O          1161
J          1119
G          1087
C          1037
E           990
Q           967
W           941
Q           892
N           765
F           753
R           682
O           655
B           596
S           514
G           497
U           489
L           482
W           471
C           433
J           423
99           53
Name: sector, dtype: int64

In [25]:
# Beat of the address associated with the underlying Computer Aided Dispatch (CAD) event. 
# Not necessarily where the Terry Stop occurred.

df['beat'].value_counts(dropna=False)

NaN       10073
N3         1175
E2         1092
K3         1054
M2          852
          ...
N1           86
99           53
99           35
OOJ          25
S             2
Name: beat, Length: 107, dtype: int64

In [26]:
# Convert Officer YOB to Age
df['officer_yob'] = 2021 - df['officer_yob']

In [27]:
df['officer_yob'].value_counts()

35     3382
34     3087
37     2798
30     2742
29     2554
36     2513
31     2341
33     2186
32     2051
39     1868
38     1743
42     1558
28     1516
40     1476
26     1304
50     1236
43     1177
45     1051
44     1030
27      963
48      933
41      838
25      728
54      721
53      632
51      612
52      568
47      565
46      539
24      486
59      457
57      439
49      429
56      420
58      262
55      228
63      220
60      215
62      174
61      161
23       60
67       44
64       43
121      35
68       34
66       21
65       17
73       11
69        9
72        5
75        2
70        1
Name: officer_yob, dtype: int64

In [28]:
# rename officer_yob column to officer age
df.rename(columns={'officer_yob':'officer_age'}, inplace=True)

In [29]:
# Inspecting age outliers 
df.nlargest(50,['officer_age'])

,subject_age_group,stop_resolution,weapon_type,officer_id,officer_age,officer_gender,officer_race,subject_perceived_race,subject_perceived_gender,reported_date,initial_call_type,final_call_type,call_type,officer_squad,arrest_flag,frisk_flag,precinct,sector,beat
1050,Not Specified,Field Contact,None,NaN,121,N,Unknown,Unknown,Unknown,2019-07-27T00:00:00,NaN,NaN,NaN,NaN,N,Y,West,K,K3
1051,Not Specified,Field Contact,None,NaN,121,N,Unknown,Unknown,Unknown,2019-07-27T00:00:00,NaN,NaN,NaN,NaN,N,Y,West,K,K3
1052,Not Specified,Field Contact,None,NaN,121,N,Unknown,Unknown,Unknown,2019-07-27T00:00:00,NaN,NaN,NaN,NaN,N,Y,West,K,K3
1071,Not Specified,Field Contact,None,NaN,121,N,Unknown,White,Male,2019-09-10T00:00:00,NaN,NaN,NaN,NaN,N,N,East,E,E3
3622,18 - 25,Field Contact,None,-9,121,N,Unknown,Black or African American,Male,2015-05-19T00:00:00,NaN,NaN,NaN,NaN,N,N,NaN,NaN,NaN
7247,18 - 25,Field Contact,None,-9,121,N,Unknown,Unknown,Female,2017-06-06T00:00:00,NaN,NaN,NaN,NaN,N,N,NaN,NaN,NaN
9277,18 - 25,Arrest,None,-9,121,N,Unknown,White,Male,2018-02-07T00:00:00,NaN,NaN,NaN,NaN,N,N,West,Q,Q1
11316,18 - 25,Field Contact,None,IV70,121,M,Unknown,Unknown,Male,2019-05-30T00:00:00,NaN,NaN,NaN,NaN,N,N,East,E,E1
11876,18 - 25,Field Contact,None,NaN,121,N,Unknown,White,Female,2019-11-27T00:00:00,NaN,NaN,NaN,NaN,N,N,West,M,M3
12519,18 - 25,Offense Report,None,NaN,121,N,Unknown,American Indian or Alaska Native,Female,2019-10-29T00:00:00,NaN,NaN,NaN,NaN,N,N,West,M,M3
20730,26 - 35,Field Contact,None,8579,121,M,Unknown,White,Female,2018-05-21T00:00:00,NaN,NaN,NaN,TRAINING - FIELD TRAINING SQUAD,N,N,NaN,NaN,NaN
25193,26 - 35,Arrest,None,NaN,121,N,Unknown,White,Female,2019-08-15T00:00:00,NaN,NaN,NaN,NaN,Y,N,North,B,B1
25518,26 - 35,Arrest,None,NaN,121,N,Unknown,White,Male,2019-10-23T00:00:00,NaN,NaN,NaN,NaN,Y,N,West,Q,Q2
27051,26 - 35,Field Contact,None,IV70,121,M,Unknown,Unknown,Male,2019-05-20T00:00:00,NaN,NaN,NaN,NaN,N,N,West,K,K3
27542,26 - 35,Field Contact,None,IV70,121,M,Unknown,White,Male,2019-05-20T00:00:00,NaN,NaN,NaN,NaN,N,N,NaN,NaN,NaN
28272,26 - 35,Field Contact,None,NaN,121,N,Unknown,White,Male,2019-11-02T00:00:00,NaN,NaN,NaN,NaN,N,N,West,D,D3
28294,26 - 35,Field Contact,None,NaN,121,N,Unknown,White,Male,2019-11-10T00:00:00,NaN,NaN,NaN,NaN,N,N,West,D,D1
30164,36 - 45,Field Contact,None,-9,121,N,Unknown,White,Female,2016-01-02T00:00:00,NaN,NaN,NaN,NaN,N,N,North,N,N3
31173,36 - 45,Field Contact,None,-9,121,N,Unknown,White,Male,2016-09-14T00:00:00,NaN,NaN,NaN,NaN,N,N,NaN,NaN,NaN
36728,36 - 45,Field Contact,None,NaN,121,N,Unknown,Unknown,Female,2019-10-28T00:00:00,NaN,NaN,NaN,NaN,N,N,West,M,M3
37009,36 - 45,Field Contact,None,NaN,121,N,Unknown,White,Female,2019-11-22T00:00:00,NaN,NaN,NaN,NaN,N,N,West,M,M3
37026,36 - 45,Arrest,None,NaN,121,N,Unknown,Black or African American,Male,2019-06-06T00:00:00,NaN,NaN,NaN,NaN,Y,Y,South,S,S1
37081,36 - 45,Field Contact,None,NaN,121,N,Unknown,Unknown,Female,2019-07-09T00:00:00,NaN,NaN,NaN,NaN,N,N,West,Q,Q2
37095,36 - 45,Offense Report,Knife/Cutting/Stabbing Instrument,IV70,121,M,Unknown,White,Male,2019-05-14T00:00:00,NaN,NaN,NaN,NaN,N,Y,NaN,NaN,NaN
37172,36 - 45,Field Contact,None,NaN,121,N,Unknown,White,Male,2019-07-21T00:00:00,NaN,NaN,NaN,NaN,N,N,West,Q,Q1
38542,36 - 45,Field Contact,None,NaN,121,N,Unknown,White,Male,2019-11-22T00:00:00,NaN,NaN,NaN,NaN,N,N,West,M,M3
38949,36 - 45,Field Contact,None,NaN,121,N,Unknown,Unknown,Female,2019-09-30T00:00:00,NaN,NaN,NaN,NaN,N,N,West,K,K2
39017,36 - 45,Field Contact,None,NaN,121,N,Unknown,White,Male,2019-11-10T00:00:00,NaN,NaN,NaN,NaN,N,N,West,D,D1
39664,36 - 45,Field Contact,None,NaN,121,N,Unknown,Unknown,Male,2019-10-24T00:00:00,NaN,NaN,NaN,NaN,N,N,West,D,D1
44405,46 - 55,Field Contact,None,NaN,121,N,Unknown,Black or African American,Male,2019-07-13T00:00:00,NaN,NaN,NaN,NaN,N,N,West,M,M1
44606,46 - 55,Offense Report,None,NaN,121,N,Unknown,American Indian or Alaska Native,Female,2019-10-23T00:00:00,NaN,NaN,NaN,NaN,N,N,West,Q,Q2
45180,46 - 55,Field Contact,None,NaN,121,N,Unknown,White,Male,2019-09-22T00:00:00,NaN,NaN,NaN,NaN,N,N,East,E,E3
45742,46 - 55,Field Contact,None,NaN,121,N,Unknown,White,Male,2019-09-29T00:00:00,NaN,NaN,NaN,NaN,N,N,West,M,M3
47294,56 and Above,Offense Report,None,8579,121,M,Unknown,Hispanic,Male,2018-07-10T00:00:00,UNKNOWN - ANI/ALI - WRLS PHNS (INCL OPEN LINE),--DISTURBANCE - OTHER,"TELEPHONE OTHER, NOT 911",TRAINING - FIELD TRAINING SQUAD,N,Y,North,B,B2
48195,56 and Above,Field Contact,None,NaN,121,N,Unknown,Unknown,Male,2019-09-22T00:00:00,NaN,NaN,NaN,NaN,N,N,East,E,E3
3920,18 - 25,Field Contact,None,4272,75,M,Asian,White,Male,2015-09-10T00:00:00,NaN,NaN,NaN,EAST PCT OPS - CPT,N,N,West,K,K1
5385,18 - 25,Field Contact,None,4272,75,M,Asian,Black or African American,Male,2016-02-22T00:00:00,NaN,NaN,NaN,EAST PCT OPS - CPT,N,N,West,K,K3
182,Not Specified,Offense Report,None,3170,73,M,White,Multi-Racial,Unknown,2015-07-14T00:00:00,NUISANCE - MISCHIEF,NUISANCE - MISCHIEF,ONVIEW,NORTH PCT 1ST W - BOY (JOHN),N,N,North,J,J3
4594,18 - 25,Citation / Infraction,None,3170,73,M,White,White,Male,2015-07-20T00:00:00,PARKS VIOLATIONS/CITES (INCLUDES EXCLUSIONS),--MISC MISD AND VIOLS - PARKS EXCLUSION,911,NORTH PCT 1ST W - BOY (JOHN),N,N,NaN,NaN,NaN
4595,18 - 25,Citation / Infraction,None,3170,73,M,White,White,Female,2015-07-20T00:00:00,PARKS VIOLATIONS/CITES (INCLUDES EXCLUSIONS),--MISC MISD AND VIOLS - PARKS EXCLUSION,911,NORTH PCT 1ST W - BOY (JOHN),N,N,NaN,NaN,NaN
4596,18 - 25,Citation / Infraction,None,3170,73,M,White,White,Male,2015-07-20T00:00:00,PARKS VIOLATIONS/CITES (INCLUDES EXCLUSIONS),--MISC MISD AND VIOLS - PARKS EXCLUSION,911,NORTH PCT 1ST W - BOY (JOHN),N,N,NaN,NaN,NaN
4829,18 - 25,Offense Report,None,3170,73,M,White,Black or African American,Female,2015-09-06T00:00:00,NaN,NaN,NaN,NORTH PCT 1ST W - BOY (JOHN),N,N,North,N,N3
14286,26 - 35,Offense Report,None,3170,73,M,White,Hispanic,Male,2015-06-12T00:00:00,THEFT (DOES NOT INCLUDE SHOPLIFT OR SVCS),"SUSPICIOUS PERSON, VEHICLE OR INCIDENT","TELEPHONE OTHER, NOT 911",NORTH PCT 1ST W - BOY (JOHN),N,Y,North,J,J3
30241,36 - 45,Offense Report,None,3170,73,M,White,White,Male,2015-08-12T00:00:00,NaN,NaN,NaN,NORTH PCT 1ST W - BOY (JOHN),N,N,North,U,U2
30242,36 - 45,Offense Report,None,3170,73,M,White,White,Male,2015-08-11T00:00:00,NaN,NaN,NaN,NORTH PCT 1ST W - BOY (JOHN),N,N,North,U,U2
40332,46 - 55,Citation / Infraction,None,3170,73,M,White,White,Female,2015-07-20T00:00:00,PARKS VIOLATIONS/CITES (INCLUDES EXCLUSIONS),--MISC MISD AND VIOLS - PARKS EXCLUSION,911,NORTH PCT 1ST W - BOY (JOHN),N,N,NaN,NaN,NaN
40397,46 - 55,Offense Report,None,3170,73,M,White,White,Male,2015-08-12T00:00:00,THREATS (INCLS IN-PERSON/BY PHONE/IN WRITING),"--ASSAULTS - HARASSMENT, THREATS",911,NORTH PCT 1ST W - BOY (JOHN),N,N,North,B,B3
46274,56 and Above,Offense Report,None,3170,73,M,White,Asian,Male,2015-08-13T00:00:00,"DISTURBANCE, MISCELLANEOUS/OTHER","DISTURBANCE, MISCELLANEOUS/OTHER",ONVIEW,NORTH PCT 1ST W - BOY (JOHN),N,N,North,B,B1
4632,18 - 25,Offense Report,None,2768,72,M,White,Black or African American,Male,2015-07-29T00:00:00,"NOISE - DISTURBANCE (PARTY, ETC)",--DISTURBANCE - NOISE,911,SOUTHWEST PCT 3RD W - FRANK,N,N,Southwest,F,F1
7659,18 - 25,Field Contact,None,6752,72,M,White,Black or African American,Unknown,2017-02-04T00:00:00,ASLT - IP/JO - PERSON SHOT OR SHOT AT,"--ASSAULTS, OTHER",911,SOUTH PCT 3RD W - OCEAN,N,N,South,O,O3

In [30]:
# dropping rows where officer age is 121 bc there is also insufficient data in those rows 
df.drop((df[df['officer_age'] == 121]).index, inplace = True)

In [32]:
# Convert reported_date column to datetime type
df['reported_date'] = pd.to_datetime(df['reported_date'], yearfirst=True)
# df['reported_date'] = pd.to_numeric(df['reported_date'])

In [40]:
# add columns for year and month
df['year'] = df['reported_date'].dt.year
df['month'] = df['reported_date'].dt.month

In [33]:
# Convert Arrest and Frisk columns to 1's and 0's
df['arrest_flag'] = df['arrest_flag'].replace({'Y':1, 'N':0})
df['frisk_flag'] = df['frisk_flag'].replace({'Y':1, 'N':0})

In [34]:
# inspecting value counts for arrest flag column
df['arrest_flag'].value_counts(dropna=False)

0    44629
1     3821
Name: arrest_flag, dtype: int64

In [35]:
# Dropping NaN's from frisk flag column bc it only represents .9% of the data set
df['frisk_flag'].value_counts(normalize=True,dropna=False)
df = df.dropna(how='any',subset=['frisk_flag'])

In [36]:
# Final Inspection of Dataframe
df.shape

(47972, 19)

In [37]:
df.head()

,subject_age_group,stop_resolution,weapon_type,officer_id,officer_age,officer_gender,officer_race,subject_perceived_race,subject_perceived_gender,reported_date,initial_call_type,final_call_type,call_type,officer_squad,arrest_flag,frisk_flag,precinct,sector,beat
0,Not Specified,Arrest,None,7500,37,M,Black or African American,Asian,Male,2015-10-16,NaN,NaN,NaN,SOUTH PCT 1ST W - ROBERT,0,0.0,South,O,O2
1,Not Specified,Field Contact,None,5670,56,M,White,Unknown,Unknown,2015-03-19,NaN,NaN,NaN,NaN,0,0.0,NaN,NaN,NaN
3,Not Specified,Field Contact,None,7539,58,M,White,Unknown,Unknown,2015-04-01,NaN,NaN,NaN,NaN,0,0.0,NaN,NaN,NaN
4,Not Specified,Field Contact,None,6973,44,M,White,Black or African American,Male,2015-04-03,NaN,NaN,NaN,NaN,0,0.0,NaN,NaN,NaN
5,Not Specified,Field Contact,None,7402,48,M,White,Black or African American,Male,2015-04-05,NaN,NaN,NaN,NaN,0,0.0,NaN,NaN,NaN

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47972 entries, 0 to 48484
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   subject_age_group         47972 non-null  object
 1   stop_resolution           47972 non-null  object
 2   weapon_type               47972 non-null  object
 3   officer_id                47972 non-null  object
 4   officer_age               47972 non-null  int64
 5   officer_gender            47972 non-null  object
 6   officer_race              47972 non-null  object
 7   subject_perceived_race    47972 non-null  object
 8   subject_perceived_gender  47972 non-null  object
 9   reported_date             47972 non-null  datetime64[ns]
 10  initial_call_type         34964 non-null  object
 11  final_call_type           34964 non-null  object
 12  call_type                 34964 non-null  object
 13  officer_squad             47412 non-null  object
 14  arrest_flag               47972 non-null  int64
 15  frisk_flag                47972 non-null  float64
 16  precinct                  38187 non-null  object
 17  sector                    37980 non-null  object
 18  beat                      38046 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(15)
memory usage: 7.3+ MB

In [39]:
# save cleaned dataframe as a csv
df.to_csv('Terry_stops_cleaned.csv', index=False)